### PR TITLE
Remove the definitions of command and thunk

### PR DESCRIPTION
**Pull request by omasanori**
These terms are defined but not really useful in pR7RS.

### CODE REVIEW

**Review by jrincayc — APPROVED** [review]
I agree with this change.

**Comment by jrincayc** [comment]
Thank you (and I added an acknowledgement in the text).

**Comment by omasanori** [comment]
Thanks!

**Comment by jrincayc** [comment]
@omasanori  Just out of curiosity, did you read the entire spec?

**Comment by omasanori** [comment]
Yes I did few times, and I am thinking about an idea of bootstrapping a Scheme compiler from pR7RS + a modified subset of I/O procedures...

**Comment by jrincayc** [comment]
Sounds good.  If you do boot strap a Scheme compiler from pR7RS let me know. :)

**Pull request merged**
